version: "3.9"

services:

  # portainer:
  #   image: portainer/portainer-ce:2.11.0
  #   container_name: portainer
  #   ports:
  #     - "9000:9000"
  #     - "8000:8000"
  #   volumes:
  #     - ./volumes/portainer_data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: always
  #   networks:
  #     - app_network
  #     - default

  react_app:
    # build: ./React_app
    container_name: react_app
    image: dav046/react_app:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - java_db
      - java_app
    networks:
      - app_network

  java_app:
    container_name: java_app
    image: dav046/java_app:1.0.0
    # build: ./
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/dbcivera
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1413
      - API_SECRET=root
    depends_on:
      - java_db
    networks:
      app_network:

  java_db:
    container_name: java_db
    image: mysql:8-oracle
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1413
      - MYSQL_DATABASE=dbcivera
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      app_network:

  # app:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     # These ports are in format <host-port>:<container-port>
  #     - '80:80' # Public HTTP Port
  #     - '443:443' # Public HTTPS Port
  #     - '81:81' # Admin Web Port
  #     # Add any other Stream port you want to expose
  #     - '21:21' # FTP
      
  #   environment:
  #     # Mysql/Maria connection parameters:
  #     DB_MYSQL_HOST: "db"
  #     DB_MYSQL_PORT: 3306
  #     DB_MYSQL_USER: "npm"
  #     DB_MYSQL_PASSWORD: "npm"
  #     DB_MYSQL_NAME: "npm"
  #     # Uncomment this if IPv6 is not enabled on your host
  #     DISABLE_IPV6: 'true'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
  #   depends_on:
  #     - db
  #   networks:
  #     - app_network
  # db:
  #   image: 'jc21/mariadb-aria:latest'
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'npm'
  #     MYSQL_DATABASE: 'npm'
  #     MYSQL_USER: 'npm'
  #     MYSQL_PASSWORD: 'npm'
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   networks:
  #     - app_network

    
volumes:
  mysql-data:

    
networks:
  app_network:
    name: app_network
    driver: bridge

  
