package com.soycivera.api.domain.historiaclinica;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.util.Date;

public record DatosListaHistoriaClinica(
        @NotNull
        Long id,
        @NotBlank
        String idpaciente,
        String tipodocumento_text,
        String documentodouble,
        String nombre_text,
        String sexo_text,
        Date fecha__nacimiento_date,
        String estado_civil_text,
        String ocupacion_text,
        String barrio_text,
        String ciudad_text,
        String direccion_text,
        String telefono_double,
        String familiar_text,
        String parentesco_text,
        String nacionalidad_text,
        Short  edad_double,
        String correo_email,
        String rh_text,
        String eps_text,
        String motivo_consulta,
        String comonosconoce,
        String enfermedades_text,
        Boolean medicamento_boolean,
        String medicamento_text,
        Boolean operacion_boolean,
        String operacion_text,
        Boolean implante_medico_boolean,
        Boolean planifica_boolean,
        Short  embarazo_double,
        Short cesarea_double,
        Short aborto_double,
        Short partos_double,
        Boolean marcapaso_boolean,
        Boolean ciclo_regularidad_boolean,
        Date ciclo_periodo_date,
        Date parto_date,
        Date fachadate,

        String peso,
        String talla,
        String grasa,
        String imc,
        String sobrepeso,
        String abdomen_alto,
        String abdomen_bajo,
        String pierna_izquierda,
        String pierna_derecha,
        String cadera,
        String cintura,
        String brazo_izquierdo,
        String brazo_derecho,
        String plan,
        String procedimiento,
        String seguimiento
) {
    public DatosListaHistoriaClinica(HistoriaClinica historiaClinica){
        this(
                historiaClinica.getId(),
                historiaClinica.getIdpaciente(),
                historiaClinica.getTipodocumento_text(),
                historiaClinica.getDocumentodouble(),
                historiaClinica.getNombre_text(),
                historiaClinica.getSexo_text(),
                historiaClinica.getFecha__nacimiento_date(),
                historiaClinica.getEstado_civil_text(),
                historiaClinica.getOcupacion_text(),
                historiaClinica.getBarrio_text(),
                historiaClinica.getCiudad_text(),
                historiaClinica.getDireccion_text(),
                historiaClinica.getTelefono_double(),
                historiaClinica.getFamiliar_text(),
                historiaClinica.getParentesco_text(),
                historiaClinica.getNacionalidad_text(),
                historiaClinica.getEdad_double(),
                historiaClinica.getCorreo_email(),
                historiaClinica.getRh_text(),
                historiaClinica.getEps_text(),
                historiaClinica.getMotivo_consulta(),
                historiaClinica.getComonosconoce(),
                historiaClinica.getEnfermedades_text(),
                historiaClinica.getMedicamento_boolean(),
                historiaClinica.getMedicamento_text(),
                historiaClinica.getOperacion_boolean(),
                historiaClinica.getOperacion_text(),
                historiaClinica.getImplante_medico_boolean(),
                historiaClinica.getPlanifica_boolean(),
                historiaClinica.getEmbarazo_double(),
                historiaClinica.getCesarea_double(),
                historiaClinica.getAborto_double(),
                historiaClinica.getPartos_double(),
                historiaClinica.getMarcapaso_boolean(),
                historiaClinica.getCiclo_regularidad_boolean(),
                historiaClinica.getCiclo_periodo_date(),
                historiaClinica.getParto_date(),
                historiaClinica.getFachadate(),
                historiaClinica.getPeso(),
                historiaClinica.getTalla(),
                historiaClinica.getGrasa(),
                historiaClinica.getImc(),
                historiaClinica.getSobrepeso(),
                historiaClinica.getAbdomen_alto(),
                historiaClinica.getAbdomen_bajo(),
                historiaClinica.getPierna_derecha(),
                historiaClinica.getPierna_izquierda(),
                historiaClinica.getCadera(),
                historiaClinica.getCintura(),
                historiaClinica.getBrazo_izquierdo(),
                historiaClinica.getBrazo_derecho(),
                historiaClinica.getPlan(),
                historiaClinica.getProcedimiento(),
                historiaClinica.getSeguimiento()
        );
    }
}
